version: '3.3'

services:
  feedbacky-server:
    env_file:
      - .env
    container_name: feedbacky-server
    ports:
      - '${SERVER_APP_PORT}:8080'
    volumes:
      - feedbacky-data:/storage-data
    image: plajer/feedbacky-server
    restart: always
  feedbacky-client:
    container_name: feedbacky-client
    environment:
      REACT_APP_SERVER_IP_ADDRESS: ${REACT_APP_SERVER_IP_ADDRESS}
      REACT_APP_SERVICE_NAME: ${REACT_APP_SERVICE_NAME}
      REACT_APP_DEFAULT_USER_AVATAR: ${REACT_APP_DEFAULT_USER_AVATAR}
    ports:
      - '${CLIENT_APP_PORT}:80'
    links:
      - feedbacky-server
    volumes:
      - feedbacky-data:/storage-data
    image: plajer/feedbacky-proxy
    restart: always

volumes:
  feedbacky-data: