name: Docker Action

on:
  workflow_dispatch: {}
  push:
    branches:
    - master
    paths:
    - client/**
    - proxy/**
    - server/**

jobs:
  BuildDocker:
    name: Build Image (${{ matrix.image }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [client, server]
    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2.0.0
      # - name: Setup multiarch
      #   uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Feedbacky Images (${{ matrix.image }})
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            plajer/feedbacky-${{ matrix.image }}:latest
  BuildDockerProxy:
    name: Build Image (proxy)
    runs-on: ubuntu-latest
    needs: BuildDocker
    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2.0.0
      # - name: Setup multiarch
      #   uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Feedbacky Images (Proxy)
        uses: docker/build-push-action@v2
        with:
          context: proxy
          file: proxy/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            plajer/feedbacky-proxy:latest
